backend:
  name: github
  repo: ba12automotive/ba12-site
  base_url: /.netlify/functions
  auth_endpoint: auth

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cars"
    label: "Car Listings"
    folder: "cars"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }